### ISSUE TITLE
External bug breaks country airport listings

### ISSUE THREAD

**Issue by E3V3A** [E3V3A/iata-arrivals-cli#3]
What seem to be an update to the FR24 API (table results), has created a bug when trying to list the airports in a given country (by name). The bug has been reported here:

* https://github.com/supercoderz/pyflightdata/issues/19

The error  can be reproduced with:
```bash
# python3 -c "from pyflightdata import FlightData;f=FlightData();f.get_airports('India');"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/cygdrive/c/cygwin64/lib/python3.8/site-packages/pyflightdata/flightdata.py", line 135, in get_airports
    return self._fr24.get_airports_data(url)
  File "/cygdrive/c/cygwin64/lib/python3.8/site-packages/pyflightdata/common_fr24.py", line 181, in get_airports_data
    data = self.get_raw_airport_data(url)
  File "/cygdrive/c/cygwin64/lib/python3.8/site-packages/pyflightdata/common_fr24.py", line 157, in get_raw_airport_data
    return self.get_raw_data(url, 'tbl-datatable', 'tbody', 'tr') or []
  File "/cygdrive/c/cygwin64/lib/python3.8/site-packages/pyflightdata/common.py", line 112, in get_raw_data
    return self.traverse(soup, elemid, elements)
  File "/cygdrive/c/cygwin64/lib/python3.8/site-packages/pyflightdata/common.py", line 103, in traverse
    res = res.find(element)
AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by E3V3A** [comment]
This bug has now been fixed in the `pyflightdata` repo.
